package com.familyhobbies.common.event;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for DomainEvent base class and concrete event classes.
 *
 * Story: S1-007 — Implement Kafka Event Classes
 * Tests: 5 test methods
 *
 * These tests verify:
 * 1. UserRegisteredEvent has correct eventType and fields
 * 2. Events auto-generate a unique eventId
 * 3. Events auto-set occurredAt timestamp and version
 * 4. UserDeletedEvent has correct eventType and fields
 * 5. Events serialize to JSON and deserialize round-trip via Jackson
 *
 * Review findings incorporated:
 * - F-14 (NOTE): UserDeletedEvent JSON serialization round-trip is covered
 *   as part of the eventsShouldSerializeToJson test. A separate test for
 *   UserDeletedEvent serialization could be added for completeness.
 *
 * NOTE: The DomainEvent base class must be updated from the Sprint 0 version
 * (which has eventId as String and source as String) to the Sprint 1 spec
 * (which has eventId as UUID, eventType as String, occurredAt as Instant,
 * and version as int). Tests define the contract — the implementation must match.
 */
class DomainEventTest {

    private ObjectMapper objectMapper;

    @BeforeEach
    void setUp() {
        objectMapper = new ObjectMapper();
        objectMapper.registerModule(new JavaTimeModule());
    }

    @Test
    @DisplayName("UserRegisteredEvent should have correct eventType and field values")
    void userRegisteredEvent_shouldHaveCorrectEventType() {
        // when
        UserRegisteredEvent event = new UserRegisteredEvent(
            1L, "jean@example.com", "Jean", "Dupont");

        // then
        assertEquals("USER_REGISTERED", event.getEventType());
        assertEquals(1L, event.getUserId());
        assertEquals("jean@example.com", event.getEmail());
        assertEquals("Jean", event.getFirstName());
        assertEquals("Dupont", event.getLastName());
    }

    @Test
    @DisplayName("UserRegisteredEvent should auto-generate eventId via DomainEvent constructor")
    void userRegisteredEvent_shouldAutoGenerateEventId() {
        // when
        UserRegisteredEvent event = new UserRegisteredEvent(
            1L, "jean@example.com", "Jean", "Dupont");

        // then
        assertNotNull(event.getEventId(),
            "eventId should be auto-generated by DomainEvent constructor");
    }

    @Test
    @DisplayName("UserRegisteredEvent should auto-set occurredAt and version via DomainEvent constructor")
    void userRegisteredEvent_shouldAutoSetTimestamp() {
        // when
        UserRegisteredEvent event = new UserRegisteredEvent(
            1L, "jean@example.com", "Jean", "Dupont");

        // then
        assertNotNull(event.getOccurredAt(),
            "occurredAt should be auto-set to Instant.now() by DomainEvent constructor");
        assertEquals(1, event.getVersion(),
            "version should default to 1");
    }

    @Test
    @DisplayName("UserDeletedEvent should have correct eventType and field values")
    void userDeletedEvent_shouldHaveCorrectEventType() {
        // when
        UserDeletedEvent event = new UserDeletedEvent(42L, DeletionType.SOFT);

        // then
        assertEquals("USER_DELETED", event.getEventType());
        assertEquals(42L, event.getUserId());
        assertEquals(DeletionType.SOFT, event.getDeletionType());
    }

    @Test
    @DisplayName("UserRegisteredEvent should serialize to JSON and deserialize round-trip")
    void eventsShouldSerializeToJson() throws Exception {
        // given
        UserRegisteredEvent event = new UserRegisteredEvent(
            1L, "jean@example.com", "Jean", "Dupont");

        // when
        String json = objectMapper.writeValueAsString(event);

        // then — verify JSON contains expected fields
        assertNotNull(json, "Serialized JSON should not be null");
        assertTrue(json.contains("\"eventType\":\"USER_REGISTERED\""),
            "JSON should contain the eventType field");
        assertTrue(json.contains("\"userId\":1"),
            "JSON should contain the userId field");
        assertTrue(json.contains("\"email\":\"jean@example.com\""),
            "JSON should contain the email field");
        assertTrue(json.contains("\"eventId\""),
            "JSON should contain the eventId field");
        assertTrue(json.contains("\"occurredAt\""),
            "JSON should contain the occurredAt field");

        // Verify deserialization round-trip
        UserRegisteredEvent deserialized = objectMapper.readValue(
            json, UserRegisteredEvent.class);
        assertEquals(event.getEventId(), deserialized.getEventId());
        assertEquals(event.getUserId(), deserialized.getUserId());
        assertEquals(event.getEmail(), deserialized.getEmail());
    }
}
