export enum ErrorCode {
  // Web (4xx)
  VALIDATION_FAILED = 'ERR_VALIDATION',
  UNAUTHORIZED = 'ERR_UNAUTHORIZED',
  FORBIDDEN = 'ERR_FORBIDDEN',
  RESOURCE_NOT_FOUND = 'ERR_NOT_FOUND',
  CONFLICT = 'ERR_CONFLICT',
  UNPROCESSABLE_ENTITY = 'ERR_UNPROCESSABLE',
  TOO_MANY_REQUESTS = 'ERR_RATE_LIMIT',

  // Server (5xx)
  INTERNAL_SERVER_ERROR = 'ERR_INTERNAL',
  BAD_GATEWAY = 'ERR_BAD_GATEWAY',
  SERVICE_UNAVAILABLE = 'ERR_UNAVAILABLE',
  GATEWAY_TIMEOUT = 'ERR_TIMEOUT',

  // Container/Infrastructure
  SERVICE_DISCOVERY_FAILURE = 'ERR_DISCOVERY',
  CIRCUIT_BREAKER_OPEN = 'ERR_CIRCUIT_BREAKER',
  KAFKA_PUBLISH_FAILURE = 'ERR_KAFKA',
  DATABASE_CONNECTION_FAILURE = 'ERR_DATABASE',
  EXTERNAL_API_FAILURE = 'ERR_EXTERNAL_API',

  // Client-side
  NETWORK_ERROR = 'ERR_NETWORK',
  UNKNOWN = 'ERR_UNKNOWN',
}
